### ISSUE TITLE
Implement Loader

### ISSUE THREAD

**Issue by sandipgarai-ta** [sandipgarai-ta/mib_v3_FE#1]
1. Demo loader has been added with this application. and you need to modify it. The loader should be relate to be MIB.

2. HTML file at : loader.component.html. (dont remove "loading" keyword from class attribute).

3. CSS file at styles.css.

**Note:
Take update of MIB_V3_FE, MIB_V3_BE, AJ_products project from git. Otherwise you will not be able to run the application.**

**Comment by sandipgarai1307** [comment]
CSS file path src/styles.css

**Comment by tadevelopertaxassist** [comment]
#1 loader solved
