### ISSUE TITLE
Home Page Quick Apply-UI fixing

### ISSUE THREAD

**Issue by sandipgarai-ta** [sandipgarai-ta/mib_v3_FE#4]
1) Need a active class for selected quick apply section.
A class already has been created for this, named by "activeQuickApplyTab" at home.component.css file. You just need to do inside this class.

![image](https://user-images.githubusercontent.com/40002907/48676600-e97d8180-eb8e-11e8-9956-e0ce82f61ef5.png)

2)Header  does not match with rest of the part of the section.
![image](https://user-images.githubusercontent.com/40002907/48676616-37928500-eb8f-11e8-8e78-ec423c8abb29.png)

**Comment by tadevelopertaxassist** [comment]
#4 done
