### ISSUE TITLE
Login/Registration UI issue

### ISSUE THREAD

**Issue by sandipgarai-ta** [sandipgarai-ta/mib_v3_FE#5]
1) Clicking on submit button, button getting hide.
Same for forgot password / registration.
![image](https://user-images.githubusercontent.com/40002907/49099707-238a0a00-f298-11e8-9a13-c187bd84a196.png)
![image](https://user-images.githubusercontent.com/40002907/49099741-33a1e980-f298-11e8-9b9b-a54f167ae443.png)

![image](https://user-images.githubusercontent.com/40002907/49099808-60560100-f298-11e8-9767-3b9295c2297d.png)

**Comment by tadevelopertaxassist** [comment]
#5 Done
