### ISSUE TITLE
Login UI improvement

### ISSUE THREAD

**Issue by sandipgarai-ta** [sandipgarai-ta/mib_v3_FE#7]
1) On email validation, validation msg ui improvement.
2)on email validation, i have added a class "has-error" in html, you need update the class with relevant css so that border of the input field get red.
![image](https://user-images.githubusercontent.com/40002907/49244450-d5127200-f435-11e8-9f6d-443de42a2431.png)

2) same for password field.

3) add login success/error msg alert under login button.

**Comment by sandipgarai-ta** [comment]
Same for registration page also.
For field specific validation message, i have added a class "invalid-validation", do what ever on this class. then you don't need work on every fields on login and registration page.

**Comment by tadevelopertaxassist** [comment]
#7 Done
